// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZ2BfB4CgO92HcmEwXbhhh1kZlSjG5ew',
    appId: '1:35973393254:web:b44ce5245a7016284036a7',
    messagingSenderId: '35973393254',
    projectId: 'cafeteria-app-unibe',
    authDomain: 'cafeteria-app-unibe.firebaseapp.com',
    storageBucket: 'cafeteria-app-unibe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOTCkNY-tKxUW17QEBXcN9_qH9Xn0aD_o',
    appId: '1:35973393254:android:d0f173631db5e6d24036a7',
    messagingSenderId: '35973393254',
    projectId: 'cafeteria-app-unibe',
    storageBucket: 'cafeteria-app-unibe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVNYp3U8TMwfC9ogOmbT3BIciIvc4CHC0',
    appId: '1:35973393254:ios:9da9ea8128ac69934036a7',
    messagingSenderId: '35973393254',
    projectId: 'cafeteria-app-unibe',
    storageBucket: 'cafeteria-app-unibe.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVNYp3U8TMwfC9ogOmbT3BIciIvc4CHC0',
    appId: '1:35973393254:ios:9da9ea8128ac69934036a7',
    messagingSenderId: '35973393254',
    projectId: 'cafeteria-app-unibe',
    storageBucket: 'cafeteria-app-unibe.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHZ2BfB4CgO92HcmEwXbhhh1kZlSjG5ew',
    appId: '1:35973393254:web:7ef7c46d85056d264036a7',
    messagingSenderId: '35973393254',
    projectId: 'cafeteria-app-unibe',
    authDomain: 'cafeteria-app-unibe.firebaseapp.com',
    storageBucket: 'cafeteria-app-unibe.firebasestorage.app',
  );

}